name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: ${{ secrets.GITHUB_USERNAME }}
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and Push Changes
        run: |
          git config user.name "AliAliyev21"
          git config user.email "actions@github.com"
          git add dist/
          git commit -m "Update contribution graph snake"
          git push origin main  # Change 'main' to your default branch name if needed

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
